version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: digitalocean.com/php
    container_name: js-vue
    restart: unless-stopped
    tty: true
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      SERVICE_NAME: js-vue
      SERVICE_TAGS: dev
      PHP_IDE_CONFIG: serverName=php-vue
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    depends_on:
      - app
    restart: on-failure
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: database-vue
    ports:
      - 2207:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webpack
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-vue
    links:
      - db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
    networks:
      - app-network

  app-vue:
    command: yarn run dev
    image: node:lts-alpine
    container_name: app-vue
    working_dir: /app
    volumes:
      - ./web/:/app
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
